# El 1er mensaje que muestra la aplicación
instrucciones = "A continuación, un verbo irregular en inglés aparecerá en pantalla. Deberás responder correctamente y en la menor cantidad de tiempo posible."

# Todos los posibles consejos que el programa puede dar al principio.
consejos = [
    "Pro tip: Presiona Ctrl + C para terminar la práctica en cualquier momento",
    "Pro tip: Presiona ⊞ Windows + Ctrl + ⇧ Shift + Alt + L si ocupas revisar LinkedIn",
    "Pro tip: Puedes escribir solamente \".\" si quieres introducir la línea previa como respuesta",
    "Pro tip: Venus es el planeta más caliente del sistema solar",
    "Pro tip: Si te sientes frustrado, toma un descanso de 5 minutos antes de continuar",
    "Pro tip: Me quedé sin consejos que dar. ¡Buena suerte! ^_^"
]

# Aquí va lo que se le solicita al usuario
# Se vincula a las respuestas por posición, entonces si tengo una pregunta en categorias[1],
# esta se vincula con datos[dato][1].
categorias = ['Past tense: ', 'Participle: ']

# Aquí se especifican las preguntas y respuestas con el formato:
# {"dato": ["respuesta1", "respuesta2" ...]}
datos = {
'abide': ['abode/abided', 'abode/abided'],
 'arise': ['arose', 'arisen'],
 'awake': ['awoke', 'awoken'],
 'is': ['was', 'been'],
 'am': ['was', 'been'],
 'are': ['were', 'been'],
 'bear(soportar)': ['bore', 'borne/born'],
 'beat': ['beat', 'beaten'],
 'become': ['became', 'become'],
 'beget': ['begat/begot', 'begotten'],
 'begin': ['began', 'begun'],
 'bend': ['bent', 'bent'],
 'bereave': ['bereft/bereaved', 'bereft/bereaved'],
 'bet': ['bet', 'bet'],
 'bid': ['bid/bade', 'bid/bidden'],
 'bleed': ['bled', 'bled'],
 'blow': ['blew', 'blown'],
 'break': ['broke', 'broken'],
 'breed': ['bred', 'bred'],
 'bring': ['brought', 'brought'],
 'broadcast': ['broadcast', 'broadcast'],
 'build': ['built', 'built'],
 'burn': ['burnt/burned', 'burnt/burned'],
 'burst': ['burst', 'burst'],
 'buy': ['bought', 'bought'],
 'can': ['could', 'could'],
 'cast': ['cast', 'cast'],
 'catch': ['caught', 'caught'],
 'chide': ['chid', 'chidden'],
 'choose': ['chose', 'chosen'],
 'cling': ['clung', 'clung'],
 'clothe': ['clad/clothed', 'clad/clothed'],
 'come': ['came', 'come'],
 'cost': ['cost', 'cost'],
 'creep': ['crept', 'crept'],
 'cut': ['cut', 'cut'],
 'deal': ['dealt', 'dealt'],
 'dig': ['dug', 'dug'],
 'dive': ['dived/dove', 'dived/dove'],
 'do': ['did', 'done'],
 'draw': ['drew', 'drawn'],
 'dream': ['dreamt/dreamed', 'dreamt/dreamed'],
 'drink': ['drank', 'drunk'],
 'drive': ['drove', 'driven'],
 'dwell': ['dwelt/dwelled', 'dwelt/dwelled'],
 'eat': ['ate', 'eaten'],
 'fall': ['fell', 'fallen'],
 'feed': ['fed', 'fed'],
 'feel': ['felt', 'felt'],
 'fight': ['fought', 'fought'],
 'find': ['found', 'found'],
 'flee': ['fled', 'fled'],
 'fling': ['flung', 'flung'],
 'fly': ['flew', 'flown'],
 'forbid': ['forbade', 'forbidden'],
 'forecast': ['forecast', 'forecast'],
 'forget': ['forgot', 'forgotten/forgot'],
 'forgive': ['forgave', 'forgiven'],
 'forsake': ['forsook', 'forsaken'],
 'foresee': ['foresaw', 'foresawn/foreseen'],
 'freeze': ['froze', 'frozen'],
 'get': ['got', 'gotten/got'],
 'give': ['gave', 'given'],
 'go': ['went', 'gone'],
 'grind': ['ground/grinded', 'ground/grinded'],
 'grow': ['grew', 'grown'],
 'hang': ['hung', 'hung'],
 'have': ['had', 'had'],
 'hear': ['heard', 'heard'],
 'hide': ['hid', 'hidden'],
 'hit': ['hit', 'hit'],
 'hold': ['held', 'held'],
 'hurt': ['hurt', 'hurt'],
 'keep': ['kept', 'kept'],
 'kneel': ['knelt/kneeled', 'knelt/kneeled'],
 'know': ['knew', 'known'],
 'lay': ['laid', 'laid'],
 'lead': ['led', 'led'],
 'lean': ['leant/leaned', 'leant/leaned'],
 'leap': ['leapt/leaped', 'leapt/leaped'],
 'learn': ['learnt', 'learnt'],
 'leave': ['left', 'left'],
 'lend': ['lent', 'lent'],
 'let': ['let', 'let'],
 'lie(arrecostarse)': ['lay', 'lain'],
 'light': ['lit/lighted', 'lit/lighted'],
 'lose': ['lost', 'lost'],
 'make': ['made', 'made'],
 'mean': ['meant', 'meant'],
 'meet': ['met', 'met'],
 'mow': ['mowed', 'mowed/mown'],
 'offset': ['offset', 'offset'],
 'overcome': ['overcame', 'overcome'],
 'partake': ['partook', 'partaken'],
 'pay': ['paid', 'paid'],
 'plead': ['pled/pleaded', 'pled/pleaded'],
 'preset': ['preset', 'preset'],
 'prove': ['proved', 'proven/proved'],
 'put': ['put', 'put'],
 'quit': ['quit', 'quit'],
 'read': ['read', 'read'],
 'relay': ['relayed', 'relayed'],
 'rend': ['rent', 'rent'],
 'rid': ['rid', 'rid'],
 'ride': ['rode', 'ridden'],
 'ring': ['rang', 'rung'],
 'rise': ['rose', 'risen'],
 'run': ['ran', 'run'],
 'saw': ['saw/sawed', 'sawn/sawed'],
 'say': ['said', 'said'],
 'see': ['saw', 'seen'],
 'seek': ['sought', 'sought'],
 'sell': ['sold', 'sold'],
 'send': ['sent', 'sent'],
 'set': ['set', 'set'],
 'shake': ['shook', 'shaken'],
 'shed': ['shed', 'shed'],
 'shine': ['shone/shined', 'shone/shined'],
 'shoe': ['shod', 'shod'],
 'shoot': ['shot', 'shot'],
 'show': ['showed', 'shown'],
 'shut': ['shut', 'shut'],
 'sing': ['sang', 'sung'],
 'sink': ['sank/sunk', 'sunk/sunken'],
 'sit': ['sat', 'sat'],
 'slay': ['slew/slayed', 'slain'],
 'sleep': ['slept', 'slept'],
 'slide': ['slid', 'slid'],
 'slink': ['slunk/slinked', 'slunk/slinked'],
 'slit': ['slit', 'slit'],
 'smell': ['smelt/smelled', 'smelt/smelled'],
 'sow': ['sowed', 'sown/sowed'],
 'speak': ['spoke', 'spoken'],
 'speed': ['sped', 'sped'],
 'spell': ['spelt', 'spelt'],
 'spend': ['spent', 'spent'],
 'spill': ['spilt/spilled', 'spilt/spilled'],
 'spin': ['spun', 'spun'],
 'spit': ['spat/spit', 'spat/spit'],
 'split': ['split', 'split'],
 'spoil': ['spoilt/spoiled', 'spoilt/spoiled'],
 'spread': ['spread', 'spread'],
 'spring': ['sprang', 'sprung'],
 'stand': ['stood', 'stood'],
 'steal': ['stole', 'stolen'],
 'stick': ['stuck', 'stuck'],
 'sting': ['stung', 'stung'],
 'stink': ['stank', 'stunk'],
 'strew': ['strewed', 'strewn/strewed'],
 'strike': ['struck', 'stricken/struck'],
 'strive': ['strove', 'striven'],
 'swear': ['swore', 'sworn'],
 'sweat': ['sweat/sweated', 'sweat/sweated'],
 'sweep': ['swept', 'swept'],
 'swell': ['swelled', 'swollen/swelled'],
 'swim': ['swam', 'swum'],
 'swing': ['swung', 'swung'],
 'take': ['took', 'taken'],
 'teach': ['taught', 'taught'],
 'tear': ['tore', 'torn'],
 'tell': ['told', 'told'],
 'think': ['thought', 'thought'],
 'thrive': ['throve/thrived', 'thriven/thrived'],
 'throw': ['threw', 'thrown'],
 'thrust': ['thrust', 'thrust'],
 'tread': ['trod', 'trodden'],
 'typeset': ['typeset', 'typeset'],
 'undergo': ['underwent', 'undergone'],
 'understand': ['understood', 'understood'],
 'wake': ['woke', 'woken'],
 'wear': ['wore', 'worn'],
 'weep': ['wept', 'wept'],
 'wet': ['wet/wetted', 'wet/wetted'],
 'win': ['won', 'won'],
 'wind': ['wound', 'wound'],
 'withdraw': ['withdrew', 'withdrawn'],
 'wring': ['wrung', 'wrung'],
 'write': ['wrote', 'written']
}